import { NextResponse } from "next/server";
import type { Channel } from "@/types";

export async function GET() {
  const channels: Channel[] = [
    // ── Spain ──
    {
      id: "rmtv",
      name: "Real Madrid TV",
      logo: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Real_Madrid_CF.svg/512px-Real_Madrid_CF.svg.png",
      stream_url: "https://rmtv.akamaized.net/hls/live/2043153/rmtv-es-web/master.m3u8",
      category: "Sports",
      country: "Spain",
      language: "Spanish",
      created_at: new Date().toISOString(),
    },
    {
      id: "gol-classics",
      name: "Gol Classics",
      logo: "https://img.icons8.com/fluency/512/soccer.png",
      stream_url: "https://d71gqtnep83vb.cloudfront.net/gol_classics/gol_classics.m3u8",
      category: "Sports",
      country: "Spain",
      language: "Spanish",
      created_at: new Date().toISOString(),
    },
    // ── France ──
    {
      id: "lequipe",
      name: "L'Equipe",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/L%27%C3%89quipe_wordmark.svg/640px-L%27%C3%89quipe_wordmark.svg.png",
      stream_url: "https://www.dailymotion.com/video/x2lefik",
      category: "Sports",
      country: "France",
      language: "French",
      created_at: new Date().toISOString(),
    },
    {
      id: "equidia",
      name: "Equidia",
      logo: "https://img.icons8.com/fluency/512/horse.png",
      stream_url: "https://raw.githubusercontent.com/Paradise-91/ParaTV/main/streams/equidia/live2.m3u8",
      category: "Sports",
      country: "France",
      language: "French",
      created_at: new Date().toISOString(),
    },
    {
      id: "trace-sport-stars",
      name: "Trace Sport Stars",
      logo: "https://cdn-icons-png.flaticon.com/512/3112/3112948.png",
      stream_url: "https://lightning-tracesport-samsungau.amagi.tv/playlist.m3u8",
      category: "Sports",
      country: "France",
      language: "French",
      created_at: new Date().toISOString(),
    },
    {
      id: "ftf-sports",
      name: "FTF Sports",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Logo_France_T%C3%A9l%C3%A9visions.svg/512px-Logo_France_T%C3%A9l%C3%A9visions.svg.png",
      stream_url: "https://1657061170.rsc.cdn77.org/HLS/FTF-LINEAR.m3u8",
      category: "Sports",
      country: "France",
      language: "French",
      created_at: new Date().toISOString(),
    },
    {
      id: "nrj12",
      name: "NRJ 12",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/NRJ12_logo_2015.svg/749px-NRJ12_logo_2015.svg.png",
      stream_url: "https://nrj12.nrjaudio.fm/hls/live/2038374/nrj_12/master.m3u8",
      category: "Entertainment",
      country: "France",
      language: "French",
      created_at: new Date().toISOString(),
    },
    {
      id: "cgtvfrench",
      name: "CGTN Francais",
      logo: "https://i.imgur.com/fMsJYzl.png",
      stream_url: "https://news.cgtn.com/resource/live/french/cgtn-f.m3u8",
      category: "News",
      country: "France",
      language: "French",
      created_at: new Date().toISOString(),
    },
    {
      id: "m6",
      name: "M6",
      logo: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Groupe_M6_Logo.png",
      stream_url: "https://origin-m6web.live.6cloud.fr/out/v1/6play/6play-m6/cmaf_q2hyb21h/index-hd720.m3u8",
      category: "Entertainment",
      country: "France",
      language: "French",
      created_at: new Date().toISOString(),
    },
    // ── USA (Spanish) ──
    {
      id: "telemundo-ny",
      name: "Telemundo NY",
      logo: "https://upload.wikimedia.org/wikipedia/commons/6/68/Telemundo_logo_2018.svg",
      stream_url: "https://nbculocallive.akamaized.net/hls/live/2037083/newyork/stream7/master.m3u8",
      category: "Sports",
      country: "USA",
      language: "Spanish",
      created_at: new Date().toISOString(),
    },
    // ── Qatar ──
    {
      id: "alkass-one",
      name: "Alkass One",
      logo: "https://logovector.net/wp-content/uploads/2013/12/al-kass-sport-channel-logo-vector-2-163055.png",
      stream_url: "https://liveeu-gcp.alkassdigital.net/alkass1-p/main.m3u8",
      category: "Sports",
      country: "Qatar",
      language: "Arabic",
      created_at: new Date().toISOString(),
    },
    {
      id: "alkass-two",
      name: "Alkass Two",
      logo: "https://logovector.net/wp-content/uploads/2013/12/al-kass-sport-channel-logo-vector-2-163055.png",
      stream_url: "https://liveeu-gcp.alkassdigital.net/alkass2-p/main.m3u8",
      category: "Sports",
      country: "Qatar",
      language: "Arabic",
      created_at: new Date().toISOString(),
    },
    // ── Morocco ──
    {
      id: "arryadia",
      name: "Arryadia",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Arryadia_logo.svg/512px-Arryadia_logo.svg.png",
      stream_url: "https://stream-lb.livemediama.com/arryadia/hls/master.m3u8",
      category: "Sports",
      country: "Morocco",
      language: "Arabic",
      created_at: new Date().toISOString(),
    },
    {
      id: "arryadia-hd1",
      name: "Arryadia HD1",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Arryadia_logo.svg/512px-Arryadia_logo.svg.png",
      stream_url: "https://stream-lb.livemediama.com/arryadia-hd-01/hls/master.m3u8",
      category: "Sports",
      country: "Morocco",
      language: "Arabic",
      created_at: new Date().toISOString(),
    },
    // ── beIN Sports ──
    {
      id: "bein-xtra",
      name: "beIN Sports XTRA",
      logo: "https://static.wikia.nocookie.net/logopedia/images/0/0b/BeIN_Xtra.PNG",
      stream_url: "https://bein-xtra-bein.amagi.tv/playlist.m3u8",
      category: "Sports",
      country: "Qatar",
      language: "Arabic",
      created_at: new Date().toISOString(),
    },
    {
      id: "bein-xtra-es",
      name: "beIN Sports XTRA Español",
      logo: "https://static.wikia.nocookie.net/logopedia/images/0/0b/BeIN_Xtra.PNG",
      stream_url: "https://dc1644a9jazgj.cloudfront.net/beIN_Sports_Xtra_Espanol.m3u8",
      category: "Sports",
      country: "USA",
      language: "Spanish",
      created_at: new Date().toISOString(),
    },
    {
      id: "bein-sports-1",
      name: "beIN Sports 1",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/BeIN_Sports_logo_%28vertical_version%29.svg/500px-BeIN_Sports_logo_%28vertical_version%29.svg.png",
      stream_url: "http://23.237.104.106:8080/USA_BEIN/index.m3u8",
      category: "Sports",
      country: "USA",
      language: "English",
      created_at: new Date().toISOString(),
    },
    // ── More Free Sports ──
    {
      id: "30a-golf",
      name: "30A Golf Kingdom",
      logo: "https://img.icons8.com/fluency/512/golf.png",
      stream_url: "https://30a-tv.com/feeds/vidaa/golf.m3u8",
      category: "Sports",
      country: "USA",
      language: "English",
      created_at: new Date().toISOString(),
    },
    {
      id: "as3-sport",
      name: "AS3 Sport TV",
      logo: "https://img.icons8.com/fluency/512/sports.png",
      stream_url: "https://streamtv.as3sport.online:3394/hybrid/play.m3u8",
      category: "Sports",
      country: "International",
      language: "English",
      created_at: new Date().toISOString(),
    },
    {
      id: "bahrain-sports-1",
      name: "Bahrain Sports 1",
      logo: "https://img.icons8.com/fluency/512/basketball.png",
      stream_url: "https://5c7b683162943.streamlock.net/live/ngrp:sportsone_all/playlist.m3u8",
      category: "Sports",
      country: "Bahrain",
      language: "Arabic",
      created_at: new Date().toISOString(),
    },
    {
      id: "cricket-gold",
      name: "Cricket Gold",
      logo: "https://img.icons8.com/fluency/512/cricket.png",
      stream_url: "https://streams2.sofast.tv/scheduler/scheduleMaster/418.m3u8",
      category: "Sports",
      country: "India",
      language: "English",
      created_at: new Date().toISOString(),
    },
    {
      id: "draftkings",
      name: "DraftKings Network",
      logo: "https://img.icons8.com/fluency/512/slot-machine.png",
      stream_url: "https://na.linear.zype.com/e0bd0e23-a958-4e43-8164-4f2fef8876a8/fd3614bd-90bf-4530-a277-65ae3a1720c8-zype/live.m3u8",
      category: "Sports",
      country: "USA",
      language: "English",
      created_at: new Date().toISOString(),
    },
    // ── Brazil (YouTube) ──
    {
      id: "cazetv",
      name: "CazéTV",
      logo: "https://img.icons8.com/fluency/512/youtube-play.png",
      stream_url: "https://www.youtube.com/@cazetvoficial/live",
      category: "Sports",
      country: "Brazil",
      language: "Portuguese",
      created_at: new Date().toISOString(),
    },
    // ── FIFA World Cup 2026 ──
    {
      id: "fox-sports-1",
      name: "Fox Sports 1",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/FOX_Sports_logo.svg/960px-FOX_Sports_logo.svg.png",
      stream_url: "https://cors-proxy.cooks.fyi/http://190.11.225.124:5000/live/fs1_hd/playlist.m3u8",
      category: "FIFA World Cup 2026",
      country: "USA",
      language: "English",
      created_at: new Date().toISOString(),
    },
    {
      id: "fox-sports-2",
      name: "Fox Sports 2",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/FOX_Sports_logo.svg/960px-FOX_Sports_logo.svg.png",
      stream_url: "https://tvsen7.aynaott.com/foxsports2/index.m3u8",
      category: "FIFA World Cup 2026",
      country: "USA",
      language: "English",
      created_at: new Date().toISOString(),
    },
    {
      id: "bbc-one",
      name: "BBC One",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/BBC_One_logo_2021.svg/960px-BBC_One_logo_2021.svg.png",
      stream_url: "https://november.queazified.co.uk/ee971134-115e-4418-8d1d-69dff7d4c6eb.m3u8",
      category: "FIFA World Cup 2026",
      country: "UK",
      language: "English",
      created_at: new Date().toISOString(),
    },
    {
      id: "bbc-two",
      name: "BBC Two",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/BBC_Two_logo_2021.svg/960px-BBC_Two_logo_2021.svg.png",
      stream_url: "https://x.canlitvapp.com/u-bbc2/index.m3u8",
      category: "FIFA World Cup 2026",
      country: "UK",
      language: "English",
      created_at: new Date().toISOString(),
    },
    {
      id: "itv1",
      name: "ITV1",
      logo: "https://i.imgur.com/xwPekCF.png",
      stream_url: "http://80.194.62.172:50002/stream/channelid/95929545",
      category: "FIFA World Cup 2026",
      country: "UK",
      language: "English",
      created_at: new Date().toISOString(),
    },
    {
      id: "canal-sport",
      name: "Canal+ Sport",
      logo: "https://i.imgur.com/EOXnU15.png",
      stream_url: "http://151.80.18.177:86/Canal+_sport_HD/index.m3u8",
      category: "FIFA World Cup 2026",
      country: "France",
      language: "French",
      created_at: new Date().toISOString(),
    },
    {
      id: "canal-foot",
      name: "Canal+ Foot",
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Canal%2BFoot.png",
      stream_url: "https://test.946985.filegear-sg.me/proxy/ef3174f16d4557d2",
      category: "FIFA World Cup 2026",
      country: "France",
      language: "French",
      created_at: new Date().toISOString(),
    },
    {
      id: "rai-sport",
      name: "Rai Sport HD",
      logo: "https://i.imgur.com/6PEevOM.png",
      stream_url: "https://srv1.adriatelekom.com/RaiSport/index.m3u8",
      category: "FIFA World Cup 2026",
      country: "Italy",
      language: "Italian",
      created_at: new Date().toISOString(),
    },
    {
      id: "ard-erde",
      name: "ARD (Das Erste)",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/ARD_Dachmarke_2014.svg/960px-ARD_Dachmarke_2014.svg.png",
      stream_url: "https://daserste-live.ard-mcdn.de/daserste/live/hls/int/master.m3u8",
      category: "FIFA World Cup 2026",
      country: "Germany",
      language: "German",
      created_at: new Date().toISOString(),
    },
    {
      id: "telemundo-intl",
      name: "Telemundo Internacional",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Telemundo_logo_2018.svg/960px-Telemundo_logo_2018.svg.png",
      stream_url: "http://138.121.15.230:9002/TELEMUNDO/index.m3u8",
      category: "FIFA World Cup 2026",
      country: "USA",
      language: "Spanish",
      created_at: new Date().toISOString(),
    },
    {
      id: "espn-deportes",
      name: "ESPN Deportes",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/ESPN_Deportes.svg/960px-ESPN_Deportes.svg.png",
      stream_url: "http://origin.thetvapp.to/hls/espn-deportes/mono.m3u8",
      category: "FIFA World Cup 2026",
      country: "USA",
      language: "Spanish",
      created_at: new Date().toISOString(),
    },
    {
      id: "tsn-ocho",
      name: "TSN The Ocho",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/TSN_%28logo%29.svg/960px-TSN_%28logo%29.svg.png",
      stream_url: "https://d3pnbvng3bx2nj.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-rds8g35qfqrnv/TSN_The_Ocho.m3u8",
      category: "FIFA World Cup 2026",
      country: "Canada",
      language: "English",
      created_at: new Date().toISOString(),
    },
    {
      id: "cctv-football",
      name: "CCTV Storm Football",
      logo: "https://i.imgur.com/Fy6HkX0.png",
      stream_url: "http://38.75.136.137:98/gslb/dsdqpub/fyzq.m3u8?auth=testpub",
      category: "FIFA World Cup 2026",
      country: "China",
      language: "Chinese",
      created_at: new Date().toISOString(),
    },
  ];

  return NextResponse.json({ channels }, {
    headers: { "Cache-Control": "no-store" },
  });
}
